app/webbackend/forms.py
from app.models import Balance, Client, Coming, Product, Sale, Stock
from flask_wtf import FlaskForm
from wtforms import (
    BooleanField,
    DateField,
    DecimalField,
    IntegerField,
    SelectField,
    StringField,
    SubmitField,
    ValidationError,
)
from wtforms.validators import DataRequired, EqualTo, Length, NumberRange, Optional


class AddProductForm(FlaskForm):
    nameproduct = StringField("Название", [DataRequired()])
    submit = SubmitField("Добавить")

    def validate_nameproduct(form, field):
        if Product.query.filter_by(nameproduct=field.data).first() is not None:
            raise ValidationError("Такой товар существует.")


class UpdateProductForm(FlaskForm):
    id = StringField("Id")
    nameproduct = StringField("Название", [DataRequired()])
    submit = SubmitField("Изменить")
    cancel = SubmitField("Отменить")

    def validate_nameproduct(form, field):
        if Product.query.filter_by(nameproduct=field.data).first() is not None:
            raise ValidationError("Такой товар существует.")


class DeleteForm(FlaskForm):
    submit = SubmitField("Удалить")
    cancel = SubmitField("Отменить")


class FilterTable(FlaskForm):
    startdate = DateField(validators=[DataRequired()], format="%d.%m.%Y")
    finishdate = DateField(validators=[DataRequired()], format="%d.%m.%Y")
    showdata = SubmitField("Показать")


class AddClientForm(FlaskForm):
    fullname = StringField("ФИО")
    phone = IntegerField("Номер телефона", [Optional()])
    status = BooleanField("Статус")
    comment = StringField("Комментарий", [Length(0, 200)])
    submit = SubmitField("Добавить")

    def validate_phone(form, field):
        if Client.query.filter_by(phone=field.data).first() is not None:
            raise ValidationError("Такой клиент существует.")


class UpdateClientForm(FlaskForm):
    fullname = StringField("ФИО")
    phone = IntegerField("Номер телефона", [Optional()])
    status = BooleanField("Статус")
    comment = StringField("Комментарий", [Length(0, 200)])
    submit = SubmitField("Изменить")
    cancel = SubmitField("Отменить")


class AddSaleForm(FlaskForm):
    client_id = SelectField("Клиент", coerce=int)
    product_id = SelectField("Товар", coerce=int)
    quantity = IntegerField("Количество", [DataRequired(), Optional()])
    price = DecimalField("Стоимость", [DataRequired(), Optional()])
    sumprice = DecimalField("Итогова сумма", [Optional()])
    status = BooleanField("Статус")
    comment = StringField("Комментарий", [Length(0, 200)])
    submit = SubmitField("Добавить")

    def validate_quantity(form, field):
        balance_quantity = Balance.query.filter_by(
            product_id=form.product_id.data
        ).first()
        if (
            not balance_quantity
            or balance_quantity.current_quantity < form.quantity.data
        ):
            raise ValidationError(
                "Товар не существует или отсутствует на складе в таком количестве"
            )


class UpdateSaleForm(FlaskForm):
    client_id = SelectField("Клиент", coerce=int)
    product_id = SelectField("Товар", coerce=int)
    quantity = IntegerField("Количество", [DataRequired(), Optional()])
    price = DecimalField("Стоимость", [DataRequired(), Optional()])
    sumprice = DecimalField("Итогова сумма", [Optional()])
    status = BooleanField("Статус")
    comment = StringField("Комментарий", [Length(0, 200)])
    submit = SubmitField("Изменить")
    cancel = SubmitField("Отменить")


class AddComingForm(FlaskForm):
    product_id = SelectField("Товар", coerce=int)
    quantity = IntegerField("Количество", [DataRequired(), Optional()])
    price = DecimalField("Стоимость", [DataRequired(), Optional()])
    sumquantity = IntegerField("Итоговое количество", [Optional()])
    sumprice = DecimalField("Итогова сумма")
    comment = StringField("Комментарий", [Length(0, 200)])
    submit = SubmitField("Добавить")


class UpdateComingForm(FlaskForm):
    product_id = SelectField("Товар", coerce=int)
    quantity = IntegerField("Количество", [DataRequired(), Optional()])
    price = DecimalField("Стоимость", [DataRequired(), Optional()])
    sumprice = DecimalField("Итогова сумма", [Optional()])
    comment = StringField("Комментарий", [Length(0, 200)])
    submit = SubmitField("Изменить")
    cancel = SubmitField("Отменить")


class UpdateBalanceForm(FlaskForm):
    product_id = SelectField("Товар", coerce=int)
    quantity = IntegerField("Количество", [DataRequired(), Optional()])
    current_quantity = IntegerField("Текущее количество", [DataRequired(), Optional()])
    price = DecimalField("Стоимость", [DataRequired(), Optional()])
    sumprice = DecimalField("Итогова сумма", [Optional()])
    submit = SubmitField("Изменить")
    cancel = SubmitField("Отменить")


class AddStockForm(FlaskForm):
    client_id = SelectField("Клиент", coerce=int)
    namestock = StringField("Название акции", [Length(0, 200)])
    nameproduct = StringField("Наименование товара", [Length(0, 200)])
    quantity = IntegerField("Количество")
    comment = StringField("Комментарий", [Length(0, 200)])
    status = BooleanField("Статус")
    submit = SubmitField("Добавить")


class UpdateStockForm(FlaskForm):
    client_id = SelectField("Клиент", coerce=int)
    namestock = StringField("Название акции", [Length(0, 200)])
    nameproduct = StringField("Наименование товара", [Length(0, 200)])
    quantity = IntegerField("Количество")
    comment = StringField("Комментарий", [Length(0, 200)])
    submit = SubmitField("Изменить")
    status = BooleanField("Статус")
    cancel = SubmitField("Отменить")

app/webbackend/views.py
from decimal import Decimal

import simplejson
from app import db
from app.models import Balance, Client, Coming, Product, Sale, Stock
from app.webbackend.forms import (
    AddClientForm,
    AddComingForm,
    AddProductForm,
    AddSaleForm,
    AddStockForm,
    DeleteForm,
    FilterTable,
    UpdateBalanceForm,
    UpdateClientForm,
    UpdateComingForm,
    UpdateProductForm,
    UpdateSaleForm,
    UpdateStockForm,
)
from app.webbackend.handlers import (
    errors_convert_dict_to_string,
    filter_for_table_between_date,
)
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user
from sqlalchemy import desc

web_blueprint = Blueprint("webbackend", __name__)


@web_blueprint.route("/product", methods=["GET", "POST"])
@login_required
def product():
    form = AddProductForm(request.form)
    if form.submit.data and form.validate_on_submit():
        product_db = Product(nameproduct=form.nameproduct.data)
        product_db.save()
        return redirect(url_for("webbackend.product"))
    elif form.is_submitted():
        flash(
            f"Ошибка ввода данных: { errors_convert_dict_to_string(form.errors) }",
            "danger",
        )
        return redirect(url_for("webbackend.product"))
    products = Product.query.all()
    return render_template("webbackend/product.html", form=form, products=products)


@web_blueprint.route("/productupdate/<int:product_id>", methods=["GET", "POST"])
@login_required
def productupdate(product_id: int):
    form = UpdateProductForm(request.form)
    product_db = Product.query.filter(Product.id == product_id).first()
    if form.is_submitted():
        if form.submit.data and form.validate():
            Product.query.filter(Product.id == product_id).update(
                {
                    "nameproduct": form.nameproduct.data,
                }
            )
            db.session.commit()
            flash("Обновлено!", "info")
            return redirect(url_for("webbackend.product"))
        elif form.cancel.data:
            return redirect(url_for("webbackend.product"))
        else:
            flash(
                f"Ошибка ввода данных: { errors_convert_dict_to_string(form.errors) }",
                "danger",
            )
            return redirect(url_for("webbackend.product"))
    return render_template(
        "webbackend/productupdate.html", form=form, product=product_db
    )


@web_blueprint.route("/productdelete/<int:product_id>", methods=["GET", "POST"])
@login_required
def productdelete(product_id: int):
    form = DeleteForm(request.form)
    product_db = Product.query.filter(Product.id == product_id).first()
    if form.is_submitted():
        if form.submit.data and product_db:
            product_db.delete()
            flash("Удалено!", "info")
            return redirect(url_for("webbackend.product"))
        elif form.cancel.data:
            return redirect(url_for("webbackend.product"))
    return render_template(
        "webbackend/productdelete.html", form=form, product=product_db
    )


@web_blueprint.route("/client", methods=["GET", "POST"])
@login_required
def client():
    form = AddClientForm(request.form)
    form_table = FilterTable(request.form)
    clients = Client.query.order_by(Client.date.desc()).all()
    if form.submit.data and form.validate_on_submit():
        client_db = Client(
            fullname=form.fullname.data,
            phone=form.phone.data,
            status=form.status.data,
            comment=form.comment.data,
        )
        client_db.save()
        return redirect(url_for("webbackend.client"))
    elif form.is_submitted() and form.submit.data:
        flash(
            f"Ошибка ввода данных: { errors_convert_dict_to_string(form.errors) }",
            "danger",
        )
        return redirect(url_for("webbackend.client"))
    if form_table.is_submitted():
        if form_table.showdata.data:
            startdate = form_table.startdate.data
            finishdate = form_table.finishdate.data
            if startdate and finishdate:
                clients = filter_for_table_between_date(Client, startdate, finishdate)
            else:
                flash(f"Ошибка ввода данных: Неверный формат даты!", "danger")
    return render_template(
        "webbackend/client.html", form=form, form_table=form_table, clients=clients
    )


@web_blueprint.route("/clientupdate/<int:client_id>", methods=["GET", "POST"])
@login_required
def clientupdate(client_id: int):
    form = UpdateClientForm(request.form)
    client_db = Client.query.filter(Client.id == client_id).first()
    if form.is_submitted():
        if form.submit.data and form.validate():
            Client.query.filter(Client.id == client_id).update(
                {
                    "fullname": form.fullname.data,
                    "phone": form.phone.data,
                    "status": form.status.data,
                    "comment": form.comment.data,
                }
            )
            db.session.commit()
            flash("Обновлено!", "info")
            return redirect(url_for("webbackend.client"))
        elif form.cancel.data:
            return redirect(url_for("webbackend.client"))
        else:
            flash(
                f"Ошибка ввода данных: { errors_convert_dict_to_string(form.errors) }",
                "danger",
            )
            return redirect(url_for("webbackend.client"))
    return render_template("webbackend/clientupdate.html", form=form, client=client_db)


@web_blueprint.route("/clientdelete/<int:client_id>", methods=["GET", "POST"])
@login_required
def clientdelete(client_id: int):
    form = DeleteForm(request.form)
    client_db = Client.query.filter(Client.id == client_id).first()
    if form.is_submitted():
        if form.submit.data and client_db:
            client_db.delete()
            flash("Удалено!", "info")
            return redirect(url_for("webbackend.client"))
        elif form.cancel.data:
            return redirect(url_for("webbackend.client"))
    return render_template("webbackend/clientdelete.html", form=form, client=client_db)


@web_blueprint.route("/sale", methods=["GET", "POST"])
@login_required
def sale():
    form = AddSaleForm(request.form)
    form_table = FilterTable(request.form)
    form.client_id.choices = [
        (client.id, client.fullname) for client in Client.query.all()
    ]
    form.product_id.choices = [(0, "Выберите товар")]
    [
        form.product_id.choices.append((product.id, product.nameproduct))
        for product in Product.query.all()
    ]
    all_balance_price = {
        balance.product_id: balance.price for balance in Balance.query.all()
    }
    all_price_json = simplejson.dumps(all_balance_price)
    sales = Sale.query.order_by(Sale.date.desc()).all()
    if form.submit.data and form.validate_on_submit():
        sale_db = Sale(
            client_id=form.client_id.data,
            product_id=form.product_id.data,
            quantity=form.quantity.data,
            price=form.price.data,
            comment=form.comment.data,
            sumprice=form.sumprice.data,
            status=form.status.data,
        )
        sale_db.save()
        if sale_db.id:
            balance_db = Balance.query.filter(
                Balance.product_id == sale_db.product_id
            ).first()
        if balance_db:
            new_quantity = balance_db.current_quantity - sale_db.quantity
            new_sumprice = balance_db.price * Decimal(new_quantity)
            Balance.query.filter(Balance.product_id == sale_db.product_id).update(
                {
                    "current_quantity": new_quantity,
                    "sumprice": new_sumprice,
                }
            )
            db.session.commit()
            return redirect(url_for("webbackend.sale"))
        else:
            flash(f"Произошла ошибка обработки. База данных не доступна.", "danger")
            return redirect(url_for("webbackend.sale"))
    elif form.is_submitted() and form.submit.data:
        flash(
            f"Ошибка ввода данных: { errors_convert_dict_to_string(form.errors) }",
            "danger",
        )
        return redirect(url_for("webbackend.sale"))
    if form_table.is_submitted():
        if form_table.showdata.data:
            startdate = form_table.startdate.data
            finishdate = form_table.finishdate.data
            if startdate and finishdate:
                sales = filter_for_table_between_date(Sale, startdate, finishdate)
            else:
                flash(f"Ошибка ввода данных: Неверный формат даты!", "danger")
    return render_template(
        "webbackend/sale.html",
        form=form,
        form_table=form_table,
        sales=sales,
        all_price=all_price_json,
    )


@web_blueprint.route("/saleupdate/<int:sale_id>", methods=["GET", "POST"])
@login_required
def saleupdate(sale_id: int):
    form = UpdateSaleForm(request.form)
    form.client_id.choices = [
        (client.id, client.fullname) for client in Client.query.all()
    ]
    form.product_id.choices = [
        (product.id, product.nameproduct) for product in Product.query.all()
    ]
    sale_db = Sale.query.filter(Sale.id == sale_id).first()
    if form.is_submitted():
        if form.submit.data and form.validate():
            Sale.query.filter(Sale.id == sale_id).update(
                {
                    "client_id": form.client_id.data,
                    "product_id": form.product_id.data,
                    "quantity": form.quantity.data,
                    "price": form.price.data,
                    "sumprice": form.sumprice.data,
                    "status": form.status.data,
                    "comment": form.comment.data,
                }
            )
            db.session.commit()
            flash("Обновлено!", "info")
            return redirect(url_for("webbackend.sale"))
        elif form.cancel.data:

app/templates/webbackend/balance.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
  <form class="form-group" role="form" action="{{ url_for('webbackend.balance') }}">
    <div class="card-header">
      <h3 class="card-title">Остатки</h3>
    </div>
    <div class="card-body">
      <div class="form-group">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Товар</th>
              <th scope="col">Количество</th>
              <th scope="col">Текущее количество</th>
              <th scope="col">Стоимость</th>
              <th scope="col">Итоговая стоимость</th>
              <th scope="col">Комментарий</th>
              <th scope="col">Редактировать</th>
              <th scope="col">Удалить</th>
            </tr>
          </thead>
          <tbody>
            {% if balances %}
            {% for balance in balances %}
            <tr>
              <th scope="row">{{loop.index}}</th>
              <td>{{ balance.product.nameproduct }}</td>
              <td>{{ balance.quantity }}</td>
              <td>{{ balance.current_quantity }}</td>
              <td>{{ balance.price }}</td>
              <td>{{ balance.sumprice }}</td>
              <td>{{ balance.comment }}</td>
              <td><a href="{{ url_for('webbackend.balanceupdate', balance_id=balance.id) }}"><span
                    class="badge badge-warning">Редактировать</span></a></td>
              <td><a href="{{ url_for('webbackend.balancedelete', balance_id=balance.id) }}"><span
                    class="badge badge-danger">Удалить</span></a></td>
            </tr>
            {% endfor %}
            {% endif %}
          </tbody>
          <tbody>
            <tr>
              <th></th>
              <td></td>
              <td></td>
              <td></td>
              <td><p class="text-right font-weight-bold ">Общая сумма:</p></td>
              <td><p class="text-left font-weight-bold ">{{ balances | sum(attribute='sumprice') }}</p></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/webbackend/client.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
  <form class="form-group" role="form" action="{{ url_for('webbackend.client') }}" method="post">
    {{ form.csrf_token }}
    <div class="card-header">
      <h3 class="card-title">Добавить клиента</h3>
    </div>
    <div class="card-body">
      <div class="form-inline">
        <div class="form-group mb-2">
          <p class="p-3 mb-4">{{form.fullname.label}}</p>
          <p class="p-3 mb-4">{{form.fullname(class='form-control')}}</p>
        </div>
        <div class="form-group mx-sm-3 mb-2">
          <p class="p-3 mb-4">{{form.phone.label}}</p>
          <p class="p-3 mb-2">{{form.phone(class='form-control', placeholder="89100000000")}}
            <small class="form-text text-muted">Введите номер телефона БЕЗ пробелов и знаков "+", "-".</small></p>
        </div>
        <div class="form-group mx-sm-3 mb-2">
          <p class="p-3 mb-4">{{form.status.label}}</p>
          <p class="p-3 mb-4">{{form.status(class='form-control')}}</p>
        </div>
        <div class="form-group mx-sm-3 mb-2">
          <p class="p-3 mb-4">{{form.comment.label}}</p>
          <p class="p-3 mb-4">{{form.comment(class='form-control')}}</p>
        </div>
        <p class="p-3 mb-4">{{form.submit(class='btn btn-primary mb-2')}}</p>
      </div>
    </div>
  </form>
    <div class="card-header">
      <h3 class="card-title">Клиенты</h3>
      <form class="form-inline" role="form" action="{{ url_for('webbackend.client') }}" method="post">
        {{ form_table.csrf_token }}
      <div class="form-group m-3">
        {{ form_table.startdate(class='form-control') }}
      </div>
      <div class="form-group mt-2">
       <p> - </p>
      </div>
      <div class="form-group m-3">
        {{ form_table.finishdate(class='form-control') }}
      </div>
        {{form_table.showdata(class='btn btn-secondary btn-sm')}}
    </form>
    </div>
    <div class="card-body">
      <div class="form-group">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Дата и Время</th>
              <th scope="col">ФИО</th>
              <th scope="col">Номер телефона</th>
              <th scope="col">Статус</th>
              <th scope="col">Комментарий</th>
              <th scope="col">Заказы</th>
              <th scope="col">Редактировать</th>
              <th scope="col">Удалить</th>
            </tr>
          </thead>
          <tbody>
            {% if clients %}
            {% for client in clients %}
            <tr>
              <th scope="row">{{loop.index}}</th>
              <td>{{ client.date.strftime('%d-%m-%Y %H:%M') }}</td>
              <td>{{ client.fullname }}</td>
              <td>{{ client.phone }}</td>
              {% if client.status %}
              <td>Выдано</td>
              {% else %}
              <td>Не выдано</td>
              {% endif %}
              <td>{{ client.comment }}</td>
              <td><a href="{{ url_for('webbackend.order', client_id=client.id) }}"><span
                    class="badge badge-success">Заказы</span></a></td>
              <td><a href="{{ url_for('webbackend.clientupdate', client_id=client.id) }}"><span
                    class="badge badge-warning">Редактировать</span></a></td>
              <td><a href="{{ url_for('webbackend.clientdelete', client_id=client.id) }}"><span
                    class="badge badge-danger">Удалить</span></a></td>
            </tr>
            {% endfor %}
            {% endif %}
          </tbody>
        </table>
      </div>
    </div>

</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
<script src="https://unpkg.com/gijgo@1.9.13/js/messages/messages.ru-ru.js" type="text/javascript"></script>
<script>
  $('#startdate').datepicker({
    uiLibrary: 'bootstrap4',
    format: 'dd.mm.yyyy',
    autoclose: true,
    locale: 'ru-ru',
  });

  $('#finishdate').datepicker({
    uiLibrary: 'bootstrap4',
    format: 'dd.mm.yyyy',
    autoclose: true,
    locale: 'ru-ru',
  });     
</script>
{% endblock %}

app/templates/webbackend/clientdelete.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
  <form class="form-group" role="form" action="{{url_for('webbackend.clientdelete', client_id=client['id']) }}"
    method="post">
    {{ form.csrf_token }}
    <div class="card-header">
      <h3 class="card-title">Удалить</h3>
    </div>
    <div class="card-body">
      <div class="form-group">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">ФИО</th>
              <th scope="col">Номер телефона</th>
              <th scope="col">Статус</th>
              <th scope="col">Комментарий</th>
              <th scope="col">Удалить</th>
              <th scope="col">Отменить</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{ client.fullname }}</td>
              <td>{{ client.phone }}</td>
              {% if client.status %}
              <td>Выдано</td>
              {% else %}
              <td>Не выдано</td>
              {% endif %}
              <td>{{ client.comment }}</td>
              <td>{{form.submit(class='btn btn-danger')}}</td>
              <td>{{form.cancel(class='btn btn-dark')}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/webbackend/clientupdate.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
  <form class="form-group" role="form" action="{{url_for('webbackend.clientupdate', client_id=client['id']) }}"
    method="post">
    {{ form.csrf_token }}
    <div class="card-header">
      <h3 class="card-title">Изменить</h3>
    </div>
    <div class="card-body">
      <div class="form-group">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">ФИО</th>
              <th scope="col">Номер телефона</th>
              <th scope="col">Статус</th>
              <th scope="col">Комментарий</th>
              <th scope="col">Изменить</th>
              <th scope="col">Отменить</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{ form.fullname(class='form-control' ,value=client.fullname) }}</td>
              <td>{{ form.phone(class='form-control' ,value=client.phone) }}</td>
              <td>{{ form.status(class='form-control' ,checked=client.status) }}</td>
              <td>{{ form.comment(class='form-control' ,value=client.comment) }}</td>
              <td>{{ form.submit(class='btn btn-danger') }}</td>
              <td>{{ form.cancel(class='btn btn-dark') }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/webbackend/product.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
  <form class="form-group" role="form" action="{{ url_for('webbackend.product') }}" method="post">
    {{ form.csrf_token }}
    <div class="card-header">
      <h3 class="card-title">Добавить товар</h3>
    </div>
    <div class="card-body">
      <div class="form-inline">
        <div class="form-group mb-2">
          <p class="p-3 mb-2">{{form.nameproduct.label}}</p>
          <p class="p-3 mb-2">{{form.nameproduct(class='form-control')}}</p>
        </div>
        <p class="p-3 mb-2">{{form.submit(class='btn btn-primary mb-2')}}</p>
      </div>
    </div>
    <div class="card-header">
      <h3 class="card-title">Товары</h3>
    </div>
    <div class="card-body">
      <div class="form-group">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Название</th>
              <th scope="col">Редактировать</th>
              <th scope="col">Удалить</th>
            </tr>
          </thead>
          <tbody>
            {% if products %}
            {% for product in products %}
            <tr>
              <th scope="row">{{loop.index}}</th>
              <td>{{ product.nameproduct }}</td>
              <td><a href="{{url_for('webbackend.productupdate', product_id=product.id) }}"><span
                    class="badge badge-warning">Редактировать</span></a></td>
              <td> <a href="{{url_for('webbackend.productdelete', product_id=product.id) }}"><span
                    class="badge badge-danger">Удалить</span></a></td>
            </tr>
            {% endfor %}
            {% endif %}
          </tbody>
        </table>
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/webbackend/productdelete.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
  <form class="form-group" role="form" action="{{url_for('webbackend.productdelete', product_id=product['id']) }}"
    method="post">
    {{ form.csrf_token }}
    <div class="card-header">
      <h3 class="card-title">Удалить</h3>
    </div>
    <div class="card-body">
      <div class="form-group">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Название</th>
              <th scope="col">Модель</th>
              <th scope="col">Удалить</th>
              <th scope="col">Отменить</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{ product.nameproduct }}</td>
              <td>{{form.submit(class='btn btn-danger')}}</td>
              <td>{{form.cancel(class='btn btn-dark')}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/webbackend/productupdate.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
  <form class="form-group" role="form" action="{{url_for('webbackend.productupdate', product_id=product['id']) }}"
    method="post">
    {{ form.csrf_token }}
    <div class="card-header">
      <h3 class="card-title">Изменить</h3>
    </div>
    <div class="card-body">
      <div class="form-group">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Название</th>
              <th scope="col">Изменить</th>
              <th scope="col">Отменить</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{{form.nameproduct(class='form-control', value = product.nameproduct)}}</td>
              <td>{{form.submit(class='btn btn-danger')}}</td>
              <td>{{form.cancel(class='btn btn-dark')}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/webbackend/saleupdate.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
  <form class="form-group" role="form" action="{{ url_for('webbackend.saleupdate', sale_id=sale['id']) }}"
    method="post">
    {{ form.csrf_token }}
    <div class="card-header">
      <h3 class="card-title">Изменить</h3>
    </div>
    <div class="card-body">
      <div class="form-group">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Клиент</th>
              <th scope="col">Товар</th>
              <th scope="col">Количество</th>
              <th scope="col">Стоимость</th>
              <th scope="col">Итоговая стоимость</th>
              <th scope="col">Статус</th>
              <th scope="col">Комментарий</th>
              <th scope="col">Изменить</th>
              <th scope="col">Отменить</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              {% set default_client_id = form.client_id.process_data(sale.client_id) %}
              {% set default_product_id = form.product_id.process_data(sale.product_id) %}
              <td>{{ form.client_id(class='form-control') }}</td>
              <td>{{ form.product_id(class='form-control') }}</td>
              <td>{{ form.quantity(class='form-control', value=sale.quantity) }}</td>
              <td>{{ form.price(class='form-control', value=sale.price) }}</td>
              <td>{{ form.sumprice(class='form-control', value=sale.sumprice) }}</td>
              <td>{{ form.status(class='form-control', checked=sale.status) }}</td>
              <td>{{ form.comment(class='form-control', value=sale.comment) }}</td>
              <td>{{ form.submit(class='btn btn-danger') }}</td>
              <td>{{ form.cancel(class='btn btn-dark') }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </form>
</div>
{% endblock %}